name: Build and push docker image

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build-and-push-docker-image:
        name: "Build and push to docker hub"
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push Docker images (latest)
                uses: docker/build-push-action@v2.7.0
                with:
                    context: './'
                    tags: |
                        giuseppemorelli/do-backup-system:latest
                    push: ${{ github.ref == 'refs/heads/main' }}

            -   name: Get the latest git tag
                uses: actions-ecosystem/action-get-latest-tag@v1
                id: latest-tag
                with:
                    semver_only: true

            -   name: Build and push Docker images (latest tag)
                uses: docker/build-push-action@v2.7.0
                with:
                    context: './'
                    tags: |
                        giuseppemorelli/do-backup-system:${{ steps.latest-tag.outputs.tag }}
                    push: ${{ github.ref == 'refs/tags/0.4.1' }}

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}

